-- Step 1: Add columns to existing tables to support bundle functionality

ALTER TABLE menu_item
ADD COLUMN IF NOT EXISTS is_bundle BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE order_item
ADD COLUMN IF NOT EXISTS selected_options TEXT;


-- Step 2: Create the new table for option groups (e.g., "Choose your Entrée")

CREATE TABLE IF NOT EXISTS menu_item_option (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    min_choices INT NOT NULL DEFAULT 1,
    max_choices INT NOT NULL DEFAULT 1,
    menu_item_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);


-- Step 3: Create the new table for the specific choices within an option group (e.g., "Samosa", "Poulet Tikka")

CREATE TABLE IF NOT EXISTS menu_item_option_choice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    price_adjustment DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    menu_item_option_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);


-- Step 4: Add the foreign key constraints to link everything together

ALTER TABLE menu_item_option
    ADD CONSTRAINT FK_option_on_menuitem
    FOREIGN KEY (menu_item_id) REFERENCES menu_item;

ALTER TABLE menu_item_option_choice
    ADD CONSTRAINT FK_choice_on_menuitem_option
    FOREIGN KEY (menu_item_option_id) REFERENCES menu_item_option;