CREATE TABLE IF NOT EXISTS special (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    restaurant_id BIGINT NOT NULL,
    title VARCHAR(255),
    description TEXT,
    image_url VARCHAR(255),
    PRIMARY KEY (id)
);

ALTER TABLE special
ADD CONSTRAINT FK_special_on_restaurant
FOREIGN KEY (restaurant_id) REFERENCES restaurant;