-- Drop the old, simple specials table
DROP TABLE IF EXISTS special;

-- Create the new table for the main Special Menu (the container)
CREATE TABLE IF NOT EXISTS special_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    restaurant_id BIGINT NOT NULL,
    title VARCHAR(255),
    subtitle VARCHAR(255),
    start_date DATE,
    end_date DATE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id),
    CONSTRAINT fk_specialmenu_on_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant
);

-- Create the new table for the items within a Special Menu
CREATE TABLE IF NOT EXISTS special_menu_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    special_menu_id BIGINT NOT NULL,
    day_title VARCHAR(255),
    name VARCHAR(255),
    description TEXT,
    PRIMARY KEY (id),
    CONSTRAINT fk_specialmenuitem_on_specialmenu FOREIGN KEY (special_menu_id) REFERENCES special_menu
);