-- Create main entity tables

CREATE TABLE customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255),
    name VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE restaurant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    has_own_ui BOOLEAN NOT NULL,
    qr_code_ordering_enabled BOOLEAN NOT NULL,
    reservations_enabled BOOLEAN NOT NULL,
    address VARCHAR(255),
    email VARCHAR(255),
    name VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE _user (
    id INT NOT NULL,
    restaurant_id BIGINT,
    email VARCHAR(255),
    password VARCHAR(255),
    PRIMARY KEY (id)
);
-- Note: We create the sequence for _user separately for better control
CREATE SEQUENCE _user_seq START WITH 1 INCREMENT BY 50;


CREATE TABLE menu_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    price DOUBLE PRECISION NOT NULL,
    restaurant_id BIGINT,
    description VARCHAR(255),
    name VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    total_price DOUBLE PRECISION NOT NULL,
    customer_id BIGINT,
    order_time TIMESTAMP(6),
    restaurant_id BIGINT,
    status VARCHAR(255) CHECK (status IN ('PENDING','CONFIRMED','PREPARING','READY_FOR_PICKUP','DELIVERED','CANCELLED')),
    table_number VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    quantity INT NOT NULL,
    menu_item_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE reservation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    party_size INT NOT NULL,
    reservation_time TIMESTAMP(6),
    restaurant_id BIGINT NOT NULL,
    customer_email VARCHAR(255),
    customer_name VARCHAR(255),
    customer_phone VARCHAR(255),
    status VARCHAR(255) CHECK (status IN ('PENDING','CONFIRMED','CANCELLED')),
    PRIMARY KEY (id)
);


-- Create foreign key constraints

ALTER TABLE IF EXISTS _user
    ADD CONSTRAINT FK_user_on_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant;

ALTER TABLE IF EXISTS menu_item
    ADD CONSTRAINT FK_menuitem_on_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant;

ALTER TABLE IF EXISTS order_item
    ADD CONSTRAINT FK_orderitem_on_menuitem FOREIGN KEY (menu_item_id) REFERENCES menu_item;

ALTER TABLE IF EXISTS order_item
    ADD CONSTRAINT FK_orderitem_on_order FOREIGN KEY (order_id) REFERENCES orders;

ALTER TABLE IF EXISTS orders
    ADD CONSTRAINT FK_order_on_customer FOREIGN KEY (customer_id) REFERENCES customer;

ALTER TABLE IF EXISTS orders
    ADD CONSTRAINT FK_order_on_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant;

ALTER TABLE IF EXISTS reservation
    ADD CONSTRAINT FK_reservation_on_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant;