-- Create the new category table
CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    restaurant_id BIGINT NOT NULL,
    parent_category_id BIGINT,
    PRIMARY KEY (id)
);

-- Add foreign key constraints for the category table
ALTER TABLE category
    ADD CONSTRAINT FK_category_on_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant;

ALTER TABLE category
    ADD CONSTRAINT FK_category_on_parent_category FOREIGN KEY (parent_category_id) REFERENCES category;

-- Add the new category_id column to the menu_item table
ALTER TABLE menu_item
    ADD COLUMN category_id BIGINT;

-- Add the foreign key constraint from menu_item to category
ALTER TABLE menu_item
    ADD CONSTRAINT FK_menuitem_on_category FOREIGN KEY (category_id) REFERENCES category;